version: "3"
services:
  web:
    image: swaingankar/my_first_repo:part1
    deploy:
      replicas: 15
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5002:80"
    networks:
      - webnet
networks:
  webnet: